### ISSUE TITLE
dokku app is not working at Materials Cloud

### ISSUE THREAD

**Issue by dou-du** [kjappelbaum/mofcolorizer#101]
This is Dou from the Materials Cloud team. I work for maintaining the dokku servers.
I found "mofcolorizer" app keeping using a high amount of CPUs ( more than 200%).
And the app seems not working:

https://mofcolorizer.materialscloud.io

Could you check this app? Thanks. 

Cheers,
Dou

**Comment by kjappelbaum** [comment]
Thanks, will take a look.



On Jul 15, 2021 at 10:52, Dou Du ***@***.******@***.***>> wrote:


This is Dou from the Materials Cloud team. I work for maintaining the dokku servers.
I found "mofcolorizer" app keeping using a high amount of CPUs ( more than 200%).
And the app seems not working:

https://mofcolorizer.materialscloud.io

Could you check this app? Thanks.

Cheers,
Dou

**Comment by kjappelbaum** [comment]
Hi Dou, 

interestingly, other things (OSSCAR marterial) appear at https://mofcolorizer.materialscloud.io.

Cheers,
Kevin

**Comment by dou-du** [comment]
> Hi Dou,
> 
> interestingly, other things (OSSCAR marterial) appear at https://mofcolorizer.materialscloud.io.
> 
> Cheers,
> Kevin

It is working now.
